# Generated by Django 3.2.22 on 2023-11-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hardwareshops_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.order_table')),
            ],
        ),
        migrations.CreateModel(
            name='products_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.category_table')),
                ('SHOPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.hardwareshops_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('bill_no', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.products_table')),
            ],
        ),
        migrations.CreateModel(
            name='return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('TRANSACTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='pro_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ORDERITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.orderitem_table')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem_table',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.products_table'),
        ),
        migrations.AddField(
            model_name='order_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.user_table'),
        ),
        migrations.CreateModel(
            name='offer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.CharField(max_length=50)),
                ('todate', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('PRODUCTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.products_table')),
            ],
        ),
        migrations.AddField(
            model_name='hardwareshops_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.login_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('HARDWARESHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.hardwareshops_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.user_table')),
            ],
        ),
    ]
