# Generated by Django 3.2.22 on 2023-11-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CH_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_table',
            name='TRANSACTION',
        ),
        migrations.RemoveField(
            model_name='return_table',
            name='quantity',
        ),
        migrations.AddField(
            model_name='return_table',
            name='ORDERITEM',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='CH_App.orderitem_table'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='pro_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('TRANSACTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CH_App.transaction')),
            ],
        ),
    ]
